#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Oct 25 15:17:44 2023

@author: matthew
"""

import random

data = [(random.randint(0, 50), random.randint(0, 50)) for i in range(10)]

print(data)
